satellite_default:
  resolution: 10
  tile_size: 5_000
  composite_method: "MEDIAN" # see geefetch.utils.enums.CompositeMethod
  aoi:
    spatial:
      left: 0
      right: 1
      bottom: 0
      top: 1
      epsg: 4326
    temporal:
      start_date: "2020-01-01"
      end_date: "2020-01-31"
  gee:
    ee_project_id: "ee-project-id"
    max_tile_size: 8 # in MB, decrease if User Memory Excess Error, choose highest possible otherwise.
